export async function GET() {
  return Response.json({
    name: "Autonomiczny Inwestor",
    version: "0.21.0",
    mode:
      "AUTONOMOUS_RESEARCH_AND_PAPER",
    marketData:
      "BINANCE_PUBLIC_MARKET_DATA_ONLY",
    automation: {
      engine: "GitHub Actions",
      targetCadence:
        "every 2 hours",
      persistenceBranch:
        "research-data",
      browserMayBeClosed: true,
      paperPortfolio: true,
      liveTrading: false,
    },
    paperPolicy: {
      startingCapitalPln: 200,
      riskPerTradePct: 0.50,
      maxOpenPositions: 3,
      maxGrossExposurePct: 100,
      maxSinglePositionPct: 50,
      dailyLossLimitPct: 2,
      hardDrawdownStopPct: 10,
      maxHoldingHours: 168,
      stop:
        "2x ATR, min 1%, max 5%",
      feePerSidePct: 0.10,
      slippagePerSidePct: 0.03,
    },
    resilience: {
      executionPreparation: {
        implemented: true,
        runtimeConnected: false,
        canSubmitOrders: false,
        durableStore: "LOCAL_SINGLE_WORKER_NOT_DEPLOYED",
        liveRiskGateIntegrated: false,
        forecastModel: "ROLLING_UP_FREQUENCY_LAPLACE_DIAGNOSTIC_ONLY",
        forecastExecutionAuthority: false,
        marketDataClosedCandlesOnly: true,
        missingClosedHourBlocksAnalysis: true,
      },
      marketDataTimeoutMs: 10000,
      marketDataMaxAttempts: 3,
      maxMarketDataStalenessHours: 4,
      heartbeatPreflightTests: true,
      ciBuildGate: true,
      healthScore: true,
      decisionJournal: true,
      persistentAlerts: true,
      shadowExecution: {
        mode: "SHADOW_NON_EXECUTABLE",
        executable: false,
        brokerConnected: false,
        brokerAdapter: "NONE",
        canSubmitOrders: false,
        persistentIntents: true,
        requiresFxAndInstrumentMapping: true,
        shadowOrderPreflight: {
          mode: "SHADOW_ONLY",
          executable: false,
          brokerConnected: false,
          brokerAdapter: "NONE",
          canSubmitOrders: false,
          deterministicRounding: true,
          minimumValidation: true,
          reconciliation: "SIMULATED_ONLY",
          auditTrail: true,
        },
        executionQuality: {
          mode: "SHADOW_ONLY",
          executable: false,
          brokerConnected: false,
          brokerAdapter: "NONE",
          canSubmitOrders: false,
          fillSimulation: true,
          publicOhlcvProxyInputs: true,
          persistentAudit: true,
          metricsBySymbol: true,
          metricsByStrategy: true,
          instrumentSpecSource: "STATIC_DIAGNOSTIC_FIXTURE_ONLY",
          fxSource: "STATIC_DIAGNOSTIC_FIXTURE_ONLY",
        },
        brokerMappingReadiness: {
          mode: "SHADOW_ONLY",
          executable: false,
          brokerConnected: false,
          brokerAdapter: "NONE",
          canSubmitOrders: false,
          instrumentSpecs: "INJECTED_DIAGNOSTIC_FIXTURE_ONLY",
          simulatedRejections: true,
        },
      },
      allocationIntelligence: {
        mode: "SHADOW_ONLY",
        paperAuthority: false,
        maxSelectedCandidates: 3,
        maxGrossWeightPct: 100,
        maxSingleWeightPct: 50,
        correlationWarning: 0.75,
        correlationHardLimit: 0.90,
        inverseVolatilityWeights: true,
        concentrationDiagnostics: true,
        automaticPaperEnforcement: false,
      },
      strategyGovernance: {
        mode: "SHADOW_ONLY",
        paperAuthority: false,
        lifecycle: ["CANDIDATE", "SHADOW", "VALIDATED", "ACTIVE", "DEGRADED", "RETIRED"],
        championChallenger: true,
        persistentState: true,
        automaticPaperEnforcement: false,
      },
      portfolioIntelligence: {
        equityCurve: true,
        expectancy: true,
        profitFactor: true,
        rMultiple: true,
        mfeMae: true,
        rollingWindowsDays: [7, 30, 90],
        strategyBreakdown: true,
        symbolBreakdown: true,
      },
      externalWatchdog: {
        engine: "GitHub Actions",
        cadence: "hourly",
        staleCriticalHours: 3.25,
        singleIssueAlert: true,
      },
    },
    marketUniverse: {
      provider: "BINANCE_SPOT_PUBLIC",
      assetClass: "CRYPTO",
      researchUniverse: 16,
      paperUniverse: 8,
      shadowResearchUniverse: 8,
      shadowPaperAuthority: false,
      expansionMode: "SHADOW_RESEARCH_FIRST",
    },
    scannerUniverse: 16,
    strategyFamilies: 4,
    allMarketScreenBars: 3000,
    deepLabBars: 5000,
    finalOosPct: 30,
    validation:
      "anchored + purged walk-forward",
    purgeBars: 24,
    storagePolicy: {
      publicResearchOnly: true,
      simulatedPaperPositionsOnly:
        true,
      secrets: false,
      realMoneyPositions: false,
      brokerData: false,
    },
    liveTrading: false,
    broker:
      "XTB_NOT_CONNECTED",
  });
}
